# Generated by Django 3.1.7 on 2021-03-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagess',
            field=models.ImageField(blank=True, upload_to=None),
        ),
    ]
