# Generated by Django 3.1.7 on 2021-03-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_imagess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagess',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
