# Generated by Django 3.1.7 on 2021-03-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210318_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='body',
            field=models.CharField(max_length=30),
        ),
    ]
