# Generated by Django 3.1.7 on 2021-03-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210320_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='body',
            field=models.TextField(),
        ),
    ]
